security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_GERANT: [ROLE_COIFFEUR, ROLE_CAISSIER]
        ROLE_COIFFEUR: ROLE_USER
        ROLE_CAISSIER: ROLE_USER